package com.consulting.camunda;

import io.camunda.zeebe.exporter.ElasticsearchExporter;
import io.camunda.zeebe.protocol.record.Record;
import io.camunda.zeebe.protocol.record.value.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class DemoExporter extends ElasticsearchExporter {

    Logger logger = LoggerFactory.getLogger(DemoExporter.class);

    @Override
    public void export(final Record<?> record) {
        if (!shouldExportRecord(record)) {
            updateLastPositionViaReflection(record.getPosition());
            return;
        }
        super.export(record);
    }

    private void updateLastPositionViaReflection(long position) {
        //reflection was generated by Cluade, need to test and verify this is the best approach to manage setting last position
        try {
            var field = ElasticsearchExporter.class.getDeclaredField("lastPosition");
            field.setAccessible(true);
            field.set(this, position);
        } catch (Exception e) {
            throw new RuntimeException("Failed to update lastPosition", e);
        }
    }


    private boolean shouldExportRecord(final Record<?> record) {
        switch (record.getValueType()) {
            case PROCESS_INSTANCE -> {
                ProcessInstanceRecordValue value = (io.camunda.zeebe.protocol.record.value.ProcessInstanceRecordValue) record.getValue();
                return value.getProcessDefinitionKey() == targetProcessDefinitionKey;
            }
            case PROCESS_INSTANCE_CREATION -> {
                ProcessInstanceCreationRecordValue value = (ProcessInstanceCreationRecordValue) record.getValue();
                return value.getProcessDefinitionKey() == targetProcessDefinitionKey;
            }
            case PROCESS_EVENT -> {
                ProcessEventRecordValue value = (ProcessEventRecordValue) record.getValue();
                return value.getProcessDefinitionKey() == targetProcessDefinitionKey;
            }
            case JOB -> {
                JobRecordValue value = (JobRecordValue) record.getValue();
                return value.getProcessDefinitionKey() == targetProcessDefinitionKey;
            }

            // here you could export variables with only a specific prefix
            case VARIABLE -> {
                VariableRecordValue value = (VariableRecordValue) record.getValue();
                return value.getName().startsWith(yourPrefix);
            }

            default -> {
                return false;
            }
        }
    }
}
